cc_binary(
    name = "fill_station_client",
    srcs = ["fill_station_client.cc"],
    deps = [
        "@com_github_grpc_grpc//:grpc++",
        "//protos:telemetry_cc_grpc",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        ],
)
