services:
  webserver:
    image: ghcr.io/cornellrocketryteam/ground-server:local
    network_mode: "host"
    # networks:
    #   - ground-network
    ports:
      - 80:80
    depends_on:
      - influxdb
  fill-telem-proxy:
    image: ghcr.io/cornellrocketryteam/fill-telem-proxy:latest
    depends_on:
      - influxdb
    network_mode: "host"
    # networks:
    #   - ground-network
    env_file:
      - ./.env.fill-telem-proxy
  rocket-telem-proxy:
    image: ghcr.io/cornellrocketryteam/rocket-telem-proxy:latest
    depends_on:
      - influxdb
    network_mode: "host"
    # networks:
    #   - ground-network
    env_file:
      - ./.env.rocket-telem-proxy
  websocket-proxy:
    image: ghcr.io/cornellrocketryteam/websocket-proxy:latest
    depends_on:
      - influxdb
      - webserver
    network_mode: "host"
    # networks:
    #   - ground-network
    ports:
      - 8080:8080
    env_file:
      - ./.env.websocket-proxy
  influxdb:
    image: influxdb:2.7.10
    network_mode: "host"
    # networks:
    #   - ground-network
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb-admin-password 
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb-admin-token
      DOCKER_INFLUXDB_INIT_ORG: crt
      DOCKER_INFLUXDB_INIT_BUCKET: telemetry
    secrets:
      - influxdb-admin-username
      - influxdb-admin-password
      - influxdb-admin-token
    volumes:
      - type: volume
        source: influxdb-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb-config
        target: /etc/influxdb2
secrets:
  influxdb-admin-username:
    file: ./.env.influxdb-admin-username
  influxdb-admin-password:
    file: ./.env.influxdb-admin-password
  influxdb-admin-token:
    file: ./.env.influxdb-admin-token
volumes:
  influxdb-data:
  influxdb-config:
# networks:
#   ground-network:
