import FuelWidget from "@/components/widgets/fuel-widget";
import GraphWidget from "@/components/widgets/graph-widget";
import MonkeyWidget from "@/components/widgets/monkey-widget";
import ValueWidget from "@/components/widgets/value-widget";
import OnOffWidget from "@/components/widgets/on-off-widget";

import type { TelemetryChannel } from "@/lib/definitions";

export const TELEMETRY_CHANNELS: TelemetryChannel[] = [
  {
    id: "pt1_pressure",
    label: "Pressure Transducer 1",
    unit: "psi",
    dbField: "pt1",
    modes: ["Value", "1m Chart", "15m Chart", "60m Chart"],
    component: GraphWidget,
  },
  {
    id: "pt2_pressure",
    label: "Pressure Transducer 2",
    unit: "psi",
    dbField: "pt2",
    modes: ["Value", "1m Chart", "15m Chart", "60m Chart"],
    component: GraphWidget,
  },
  {
    id: "lc1",
    label: "Load Cell 1",
    unit: "lbf",
    dbField: "lc1",
    modes: ["Value", "1m Chart", "15m Chart", "60m Chart"],
    component: GraphWidget,
  },
  {
    id: "ign1_cont",
    label: "Igniter 1 Continuity",
    dbField: "ign1_cont",
    modes: ["Value", "1m Chart", "15m Chart", "60m Chart"],
    component: GraphWidget,
  },
  {
    id: "ign2_cont",
    label: "Igniter 2 Continuity",
    dbField: "ign2_cont",
    modes: ["Value", "1m Chart", "15m Chart", "60m Chart"],
    component: GraphWidget,
  },
  {
    id: "pt3_pressure",
    label: "Pressure Transducer 3",
    unit: "psi",
    dbField: "pt3",
    modes: ["Value", "1m Chart", "15m Chart", "60m Chart"],
    component: GraphWidget,
  },
  {
    id: "pt4_pressure",
    label: "Pressure Transducer 4",
    unit: "psi",
    dbField: "pt4",
    modes: ["Value", "1m Chart", "15m Chart", "60m Chart"],
    component: GraphWidget,
  },
  {
    id: "rtd_temp",
    label: "RTD Temp",
    unit: "C",
    dbField: "rtd_temp",
    modes: ["Value", "1m Chart", "15m Chart", "60m Chart"],
    component: GraphWidget,
  },
  {
    id: "fuel",
    label: "Fuel",
    dbField: "fuel",
    modes: ["3D Illustration"],
    component: FuelWidget,
  },
  {
    id: "blims",
    label: "BLiMS",
    dbField: "blims",
    modes: ["3D Illustration"],
    component: MonkeyWidget,
  },
  {
    id: "alt_armed",
    label: "Altimeter Armed",
    dbField: "alt_armed",
    modes: ["Value"],
    component: OnOffWidget("Armed", "Disarmed"),
  },
  {
    id: "alt_valid",
    label: "Altimeter Valid",
    dbField: "alt_valid",
    modes: ["Value"],
    component: OnOffWidget("Valid", "Off"),
  },
  {
    id: "gps_valid",
    label: "GPS Valid",
    dbField: "gps_valid",
    modes: ["Value"],
    component: OnOffWidget("Valid", "Off"),
  },
  {
    id: "imu_valid",
    label: "IMU Valid",
    dbField: "imu_valid",
    modes: ["Value"],
    component: OnOffWidget("Valid", "Off"),
  },
  {
    id: "acc_valid",
    label: "Acceleromter Valid",
    dbField: "acc_valid",
    modes: ["Value"],
    component: OnOffWidget("Valid", "Off"),
  },
  {
    id: "adc_valid",
    label: "ADC Valid",
    dbField: "adc_valid",
    modes: ["Value"],
    component: OnOffWidget("Valid", "Off"),
  },
  {
    id: "fram_valid",
    label: "FRAM Valid",
    dbField: "fram_valid",
    modes: ["Value"],
    component: OnOffWidget("Valid", "Off"),
  },
  {
    id: "sd_valid",
    label: "SD Valid",
    dbField: "sd_valid",
    modes: ["Value"],
    component: OnOffWidget("Valid", "Off"),
  },
  {
    id: "gps_msg_valid",
    label: "GPS Message Valid",
    dbField: "gps_msg_valid",
    modes: ["Value"],
    component: OnOffWidget("Fresh", "Stale"),
  },
  {
    id: "mav_state",
    label: "MAV State",
    dbField: "mav_state",
    modes: ["Value"],
    component: OnOffWidget("On", "Off"),
  },
  {
    id: "sv2_state",
    label: "SV2 State",
    dbField: "sv2_state",
    modes: ["Value"],
    component: OnOffWidget("On", "Off"),
  },
  {
    id: "flight_mode",
    label: "Flight Mode",
    dbField: "flight_mode",
    modes: ["Value"],
    component: ValueWidget,
  },
  {
    id: "ms_since_boot",
    label: "MS since Boot",
    unit: "ms",
    dbField: "ms_since_boot",
    modes: ["Value"],
    component: ValueWidget,
  },
];
