// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: protos/command_grpc.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FillStationTelemeter_StreamTelemetry_FullMethodName = "/command.FillStationTelemeter/StreamTelemetry"
)

// FillStationTelemeterClient is the client API for FillStationTelemeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FillStationTelemeterClient interface {
	// Sends telemetry
	StreamTelemetry(ctx context.Context, in *FillStationTelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FillStationTelemetry], error)
}

type fillStationTelemeterClient struct {
	cc grpc.ClientConnInterface
}

func NewFillStationTelemeterClient(cc grpc.ClientConnInterface) FillStationTelemeterClient {
	return &fillStationTelemeterClient{cc}
}

func (c *fillStationTelemeterClient) StreamTelemetry(ctx context.Context, in *FillStationTelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FillStationTelemetry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FillStationTelemeter_ServiceDesc.Streams[0], FillStationTelemeter_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FillStationTelemetryRequest, FillStationTelemetry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FillStationTelemeter_StreamTelemetryClient = grpc.ServerStreamingClient[FillStationTelemetry]

// FillStationTelemeterServer is the server API for FillStationTelemeter service.
// All implementations must embed UnimplementedFillStationTelemeterServer
// for forward compatibility.
type FillStationTelemeterServer interface {
	// Sends telemetry
	StreamTelemetry(*FillStationTelemetryRequest, grpc.ServerStreamingServer[FillStationTelemetry]) error
	mustEmbedUnimplementedFillStationTelemeterServer()
}

// UnimplementedFillStationTelemeterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFillStationTelemeterServer struct{}

func (UnimplementedFillStationTelemeterServer) StreamTelemetry(*FillStationTelemetryRequest, grpc.ServerStreamingServer[FillStationTelemetry]) error {
	return status.Errorf(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedFillStationTelemeterServer) mustEmbedUnimplementedFillStationTelemeterServer() {}
func (UnimplementedFillStationTelemeterServer) testEmbeddedByValue()                              {}

// UnsafeFillStationTelemeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FillStationTelemeterServer will
// result in compilation errors.
type UnsafeFillStationTelemeterServer interface {
	mustEmbedUnimplementedFillStationTelemeterServer()
}

func RegisterFillStationTelemeterServer(s grpc.ServiceRegistrar, srv FillStationTelemeterServer) {
	// If the following call pancis, it indicates UnimplementedFillStationTelemeterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FillStationTelemeter_ServiceDesc, srv)
}

func _FillStationTelemeter_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FillStationTelemetryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FillStationTelemeterServer).StreamTelemetry(m, &grpc.GenericServerStream[FillStationTelemetryRequest, FillStationTelemetry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FillStationTelemeter_StreamTelemetryServer = grpc.ServerStreamingServer[FillStationTelemetry]

// FillStationTelemeter_ServiceDesc is the grpc.ServiceDesc for FillStationTelemeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FillStationTelemeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "command.FillStationTelemeter",
	HandlerType: (*FillStationTelemeterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _FillStationTelemeter_StreamTelemetry_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/command_grpc.proto",
}

const (
	RocketTelemeter_StreamTelemetry_FullMethodName = "/command.RocketTelemeter/StreamTelemetry"
)

// RocketTelemeterClient is the client API for RocketTelemeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RocketTelemeterClient interface {
	// Sends telemetry
	StreamTelemetry(ctx context.Context, in *RocketTelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RocketTelemetry], error)
}

type rocketTelemeterClient struct {
	cc grpc.ClientConnInterface
}

func NewRocketTelemeterClient(cc grpc.ClientConnInterface) RocketTelemeterClient {
	return &rocketTelemeterClient{cc}
}

func (c *rocketTelemeterClient) StreamTelemetry(ctx context.Context, in *RocketTelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RocketTelemetry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RocketTelemeter_ServiceDesc.Streams[0], RocketTelemeter_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RocketTelemetryRequest, RocketTelemetry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RocketTelemeter_StreamTelemetryClient = grpc.ServerStreamingClient[RocketTelemetry]

// RocketTelemeterServer is the server API for RocketTelemeter service.
// All implementations must embed UnimplementedRocketTelemeterServer
// for forward compatibility.
type RocketTelemeterServer interface {
	// Sends telemetry
	StreamTelemetry(*RocketTelemetryRequest, grpc.ServerStreamingServer[RocketTelemetry]) error
	mustEmbedUnimplementedRocketTelemeterServer()
}

// UnimplementedRocketTelemeterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRocketTelemeterServer struct{}

func (UnimplementedRocketTelemeterServer) StreamTelemetry(*RocketTelemetryRequest, grpc.ServerStreamingServer[RocketTelemetry]) error {
	return status.Errorf(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedRocketTelemeterServer) mustEmbedUnimplementedRocketTelemeterServer() {}
func (UnimplementedRocketTelemeterServer) testEmbeddedByValue()                         {}

// UnsafeRocketTelemeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RocketTelemeterServer will
// result in compilation errors.
type UnsafeRocketTelemeterServer interface {
	mustEmbedUnimplementedRocketTelemeterServer()
}

func RegisterRocketTelemeterServer(s grpc.ServiceRegistrar, srv RocketTelemeterServer) {
	// If the following call pancis, it indicates UnimplementedRocketTelemeterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RocketTelemeter_ServiceDesc, srv)
}

func _RocketTelemeter_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RocketTelemetryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RocketTelemeterServer).StreamTelemetry(m, &grpc.GenericServerStream[RocketTelemetryRequest, RocketTelemetry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RocketTelemeter_StreamTelemetryServer = grpc.ServerStreamingServer[RocketTelemetry]

// RocketTelemeter_ServiceDesc is the grpc.ServiceDesc for RocketTelemeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RocketTelemeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "command.RocketTelemeter",
	HandlerType: (*RocketTelemeterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _RocketTelemeter_StreamTelemetry_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/command_grpc.proto",
}

const (
	Commander_SendCommand_FullMethodName = "/command.Commander/SendCommand"
)

// CommanderClient is the client API for Commander service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommanderClient interface {
	// Sends a command and returns a reply
	SendCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*CommandReply, error)
}

type commanderClient struct {
	cc grpc.ClientConnInterface
}

func NewCommanderClient(cc grpc.ClientConnInterface) CommanderClient {
	return &commanderClient{cc}
}

func (c *commanderClient) SendCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*CommandReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandReply)
	err := c.cc.Invoke(ctx, Commander_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommanderServer is the server API for Commander service.
// All implementations must embed UnimplementedCommanderServer
// for forward compatibility.
type CommanderServer interface {
	// Sends a command and returns a reply
	SendCommand(context.Context, *Command) (*CommandReply, error)
	mustEmbedUnimplementedCommanderServer()
}

// UnimplementedCommanderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommanderServer struct{}

func (UnimplementedCommanderServer) SendCommand(context.Context, *Command) (*CommandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedCommanderServer) mustEmbedUnimplementedCommanderServer() {}
func (UnimplementedCommanderServer) testEmbeddedByValue()                   {}

// UnsafeCommanderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommanderServer will
// result in compilation errors.
type UnsafeCommanderServer interface {
	mustEmbedUnimplementedCommanderServer()
}

func RegisterCommanderServer(s grpc.ServiceRegistrar, srv CommanderServer) {
	// If the following call pancis, it indicates UnimplementedCommanderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Commander_ServiceDesc, srv)
}

func _Commander_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommanderServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Commander_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommanderServer).SendCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

// Commander_ServiceDesc is the grpc.ServiceDesc for Commander service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Commander_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "command.Commander",
	HandlerType: (*CommanderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommand",
			Handler:    _Commander_SendCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/command_grpc.proto",
}
