cc_library(
    name = "smdriver",
    hdrs = ["steppermotor.h"],
    srcs  = ["steppermotor.cpp"], 
    deps = ["//fill/lib/WiringPi:wiringpi"],
    visibility = [
        "//fill:__subpackages__",
        ],
)